kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: trustify-xtask
  labels:
    app.kubernetes.io/name: trustify-dumps-create-dump
    app.kubernetes.io/component: create-dump
    app.kubernetes.io/part-of: trustify-dumps
spec:
  runPolicy: Serial
  nodeSelector:
    kubernetes.io/arch: arm64
  triggers:
    - type: ImageChange
    - type: ConfigChange
  source:
    dockerfile: |
      FROM ghcr.io/trustification/xtask:latest
      USER 0
      RUN dnf install -y unzip
      USER trustify
      RUN \
        curl "https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip" -o "awscliv2.zip" && \
        unzip awscliv2.zip && \
        ./aws/install && \
        rm -Rf aws
      RUN /usr/local/bin/aws --version
      WORKDIR /app

  strategy:
    type: Docker
    dockerStrategy: { }
  output:
    to:
      kind: "ImageStreamTag"
      name: "trustify-xtask:latest"
